apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cs3219-db
  namespace: cs3219
spec:
  selector:
    matchLabels:
      app: cs3219-db
  serviceName: cs3219-db
  replicas: 1
  template:
    metadata:
      labels:
        app: cs3219-db
    spec:
      containers:
      - name: cs3219-db
        image: cs3219/mariadb:1.0.0
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_DATABASE
            value: cs3219
          - name: MYSQL_ROOT_PASSWORD
            value: password
